
-- Create custom types
create type public.user_role as enum ('admin', 'user');
create type public.data_item_type as enum ('document', 'link', 'key', 'image');
create type public.activity_log_action as enum ('UPLOADED', 'EDITED', 'VIEWED', 'COPIED', 'DELETED');
create type public.notification_type as enum ('broadcast', 'personal');

-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  name varchar(255),
  avatar_url varchar(255),
  role user_role default 'user'::public.user_role
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table public.profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on public.profiles
  for update using ((select auth.uid()) = id);

-- This trigger automatically creates a profile for new users.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Create a table for data_items
create table public.data_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title varchar(255) not null,
  type data_item_type not null,
  file_url text,
  link_url text,
  text_content text,
  created_by uuid references public.profiles on delete cascade not null,
  updated_by uuid references public.profiles on delete set null,
  updated_at timestamp with time zone not null default now()
);

-- Set up Row Level Security for data_items
alter table public.data_items
  enable row level security;

create policy "Data items are viewable by everyone." on public.data_items
  for select using (true);

create policy "Users can insert their own data items." on public.data_items
  for insert with check ((select auth.uid()) = created_by);

create policy "Users can update their own data items." on public.data_items
  for update using ((select auth.uid()) = created_by);

create policy "Users can delete their own data items." on public.data_items
  for delete using ((select auth.uid()) = created_by);

create policy "Admins can do anything." on public.data_items
  for all using ((select auth.uid() in (select id from public.profiles where role = 'admin'::public.user_role)));


-- Create a table for activity_logs
create table public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  item_id bigint references public.data_items on delete set null,
  action activity_log_action not null,
  item_title varchar(255),
  timestamp timestamp with time zone not null default now()
);

-- Set up Row Level Security for activity_logs
alter table public.activity_logs
  enable row level security;

create policy "Admins can view all logs." on public.activity_logs
  for select using ((select auth.uid() in (select id from public.profiles where role = 'admin'::public.user_role)));

create policy "Users can insert logs for their own actions." on public.activity_logs
  for insert with check ((select auth.uid()) = user_id);


-- Create a table for notifications
create table public.notifications (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles on delete set null,
  receiver_id uuid references public.profiles on delete set null,
  message text not null,
  type notification_type not null,
  is_read boolean default false,
  timestamp timestamp with time zone not null default now()
);

-- Set up Row Level Security for notifications
alter table public.notifications
  enable row level security;

create policy "Users can view their own notifications and broadcasts." on public.notifications
  for select using (receiver_id is null or (select auth.uid()) = receiver_id);

create policy "Admins can send broadcasts." on public.notifications
  for insert with check (((select auth.uid()) in (select id from public.profiles where role = 'admin'::public.user_role)));

create policy "Users can update their own notifications (e.g., mark as read)." on public.notifications
  for update using ((select auth.uid()) = receiver_id);

