-- Create custom types (enums) for role, item type, and action
create type public.user_role as enum ('admin', 'user');
create type public.data_item_type as enum ('document', 'link', 'key', 'image');
create type public.activity_log_action as enum ('UPLOADED', 'EDITED', 'VIEWED', 'COPIED', 'DELETED', 'DOWNLOADED');
create type public.notification_type as enum ('broadcast', 'personal');

-- Create the profiles table to store user-specific data
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  name text,
  email text,
  avatar_url text,
  role public.user_role default 'user'::public.user_role,
  created_at timestamptz default now(),

  primary key (id),
  unique(email)
);
-- Comment on table and columns
comment on table public.profiles is 'Profile data for each user.';
comment on column public.profiles.id is 'References the user in auth.users.';

-- Create the data_items table for storing assets
create table public.data_items (
  id uuid not null default gen_random_uuid(),
  title text not null,
  type public.data_item_type not null,
  file_url text,
  link_url text,
  text_content text,
  created_by uuid references public.profiles,
  updated_by uuid references public.profiles,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  primary key (id)
);
-- Comment on table
comment on table public.data_items is 'Stores all digital assets like documents, links, and keys.';

-- Create the activity_logs table for audit trails
create table public.activity_logs (
  id bigint generated by default as identity,
  user_id uuid references public.profiles,
  item_id uuid references public.data_items on delete cascade,
  action public.activity_log_action not null,
  item_title text,
  timestamp timestamptz default now(),

  primary key (id)
);
-- Comment on table
comment on table public.activity_logs is 'Records all user actions for auditing purposes.';


-- Create the notifications table
create table public.notifications (
  id bigint generated by default as identity,
  sender_id uuid references public.profiles,
  receiver_id uuid references public.profiles, -- null for broadcast
  message text not null,
  type public.notification_type not null,
  is_read boolean default false,
  timestamp timestamptz default now(),

  primary key (id)
);
-- Comment on table
comment on table public.notifications is 'Stores system and user-generated notifications.';


-- Function to automatically create a profile when a new user signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'avatar_url'
   );
  return new;
end;
$$;

-- Trigger to call the function when a new user is added to auth.users
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Function to check if a user is an admin
create or replace function public.is_admin(user_id uuid)
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  user_role public.user_role;
begin
  select role into user_role from public.profiles where id = user_id;
  return user_role = 'admin';
end;
$$;

--
-- RLS (Row-Level Security) POLICIES
--

-- Profiles Table RLS
alter table public.profiles enable row level security;

create policy "Users can view all profiles" on public.profiles
  for select using (true);

create policy "Users can insert their own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Data Items Table RLS
alter table public.data_items enable row level security;

create policy "Users can view all data items" on public.data_items
  for select using (true);

create policy "Users can insert their own data items" on public.data_items
  for insert with check (auth.uid() = created_by);

create policy "Users can update their own data items" on public.data_items
  for update using (auth.uid() = created_by);

create policy "Users can delete their own data items" on public.data_items
  for delete using (auth.uid() = created_by);

create policy "Admins can do anything on data items" on public.data_items
  for all using (public.is_admin(auth.uid()));


-- Activity Logs Table RLS
alter table public.activity_logs enable row level security;

create policy "Admins can view all activity logs" on public.activity_logs
  for select using (public.is_admin(auth.uid()));

create policy "Users can insert their own activity logs" on public.activity_logs
  for insert with check (auth.uid() = user_id);

-- Notifications Table RLS
alter table public.notifications enable row level security;

create policy "Users can view their own notifications or broadcasts" on public.notifications
  for select using (receiver_id is null or auth.uid() = receiver_id);

create policy "Admins can send broadcasts" on public.notifications
  for insert with check (public.is_admin(auth.uid()) and type = 'broadcast'::public.notification_type);